### ISSUE TITLE
Replace Redis with Valkey

### ISSUE THREAD

**Issue by tmokmss** [aws-samples/dify-self-hosted-on-aws#1]
Elasticache [now supports](https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-elasticache-valkey/) Valkey as an engine. There is cost advantage: Valkey with Serverless priced 33% lower and node-based priced 20% lower than other supported engines.

Valkey is said to be a drop-in replacement for Redis, so we should be able to replace it without any issue.

CloudFormation seems to support Valkey already.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#cfn-elasticache-replicationgroup-engine

**Comment by tmokmss** [comment]
Dify cannot be used with Redis Cluster mode (which is the only option for Valkey Serverless) because Celery does not support it. https://github.com/celery/celery/issues/2852

**Comment by tmokmss** [comment]
closed by cc72702

**Comment by amar-kamat** [comment]
We were able to use valkey serveless (drop in replacement) for nodejs, python and springboot setup. But we saw the CROSSSLOT error in 1 setup using Jedis. We will enable cluster mode and test again. Just FYI.
